update pkg to dart 3.12.1

diff --git a/inner/pkg/dart2wasm/tool/compile_benchmark b/inner/pkg/dart2wasm/tool/compile_benchmark
--- a/inner/pkg/dart2wasm/tool/compile_benchmark
+++ b/inner/pkg/dart2wasm/tool/compile_benchmark
@@ -17,28 +17,12 @@ function follow_links() {
   echo "$file"
 }
 
-function host_arch() {
-  # Use uname to determine the host architecture.
-  case `uname -m` in
-    x86_64)
-    echo "X64"
-    ;;
-    aarch64 | arm64 | armv8*)
-    echo "ARM64"
-    ;;
-    *)
-    echo "Unknown host architecture" `uname -m` >&2
-    exit 1
-    ;;
-  esac
-}
-
 # Unlike $0, $BASH_SOURCE points to the absolute path of this file.
 PROG_NAME="$(follow_links "$BASH_SOURCE")"
 
 # Handle the case where dart-sdk/bin has been symlinked to.
 PROG_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
-SDK_DIR="$(cd "${PROG_DIR}/../../.." ; pwd -P)"
+source "$PROG_DIR/utils.sh"
 
 # Locate build directory, containing executables, snapshots and platform dill.
 if [[ `uname` == 'Darwin' ]]; then
@@ -46,7 +30,7 @@ if [[ `uname` == 'Darwin' ]]; then
 else
   OUT_DIR="$SDK_DIR/out"
 fi
-HOST_ARCH="$(host_arch)"
+HOST_ARCH="$(get_host_arch | tr '[:lower:]' '[:upper:]')"
 DART_CONFIGURATION=${DART_CONFIGURATION:-Release$HOST_ARCH}
 BIN_DIR="$OUT_DIR/$DART_CONFIGURATION"
 
@@ -55,30 +39,22 @@ DART="$BIN_DIR/dart"
 DART_AOT_RUNTIME="$BIN_DIR/dartaotruntime"
 LIBRARIES_JSON_ARG="--libraries-spec=$SDK_DIR/sdk/lib/libraries.json"
 
-function find_flags {
-  echo -en "$(sed -n "/$1 =/,/end of $1/ p" $SDK_DIR/pkg/dartdev/lib/src/commands/compile.dart  | sed  '1d' | sed '$d' | tr '\n' ' ' | sed 's#\s\+# #g' | sed 's#^\s\+##' | sed 's#\s\+$##')"
-}
-# Use same flags as `dart compile exe`
-BINARYEN_FLAGS=($(find_flags 'binaryenFlags'))
-OPT_FLAGS_L0=($(find_flags 'optimizationLevel0Flags'))
-OPT_FLAGS_L1=($(find_flags 'optimizationLevel1Flags'))
-OPT_FLAGS_L2=($(find_flags 'optimizationLevel2Flags'))
-OPT_FLAGS_L3=($(find_flags 'optimizationLevel3Flags'))
-OPT_FLAGS_L4=($(find_flags 'optimizationLevel4Flags'))
-
 RUN_BINARYEN=1
 RUN_SRC=0
 GENERATE_SOURCE_MAP=1
 COMPILE_BENCHMARK_BASE_NAME=""
 PLATFORM_FILENAME="$BIN_DIR/dart2wasm_platform.dill"
 SNAPSHOT_NAME="dart2wasm"
+RUN_BENCHMARK=0
+USE_TEMP_OUTPUT=0
 
 # All arguments will be passed along to dart2wasm except specially recognized
 # flags.
 VM_ARGS=()
 DART2WASM_ARGS=("--require-js-string-builtin")
 DART_FILE=""
-WASM_FILE=""
+OUTPUT_FILE=""
+PHASES=""
 while [ $# -gt 0 ]; do
     case "$1" in
       --compile-benchmark=*)
@@ -91,14 +67,32 @@ while [ $# -gt 0 ]; do
       shift
       ;;
 
+    --run)
+      RUN_BENCHMARK=1
+      RUN_BENCHMARK_SHELL="d8"
+      shift
+      ;;
+
+    --run=*)
+      RUN_BENCHMARK=1
+      RUN_BENCHMARK_SHELL="${1#--run=}"
+      shift
+      ;;
+
+    --temp-output)
+      USE_TEMP_OUTPUT=1
+      shift
+      ;;
+
     --js-compatibility)
       PLATFORM_FILENAME="$BIN_DIR/dart2wasm_js_compatibility_platform.dill"
       DART2WASM_ARGS+=("--js-compatibility")
       shift
       ;;
 
-    -g | --no-strip-wasm)
-      BINARYEN_FLAGS+=("-g")
+    --standalone)
+      PLATFORM_FILENAME="$BIN_DIR/dart2wasm_standalone_platform.dill"
+      DART2WASM_ARGS+=("--standalone")
       shift
       ;;
 
@@ -108,33 +102,20 @@ while [ $# -gt 0 ]; do
       shift
       ;;
 
-    -O0 | --optimization-level=0)
-      DART2WASM_ARGS+=(${OPT_FLAGS_L0[@]})
+    -O0 | --optimization-level=0 | --extra-compiler-option=-O0 )
+      DART2WASM_ARGS+=("-O0")
       RUN_BINARYEN=0
       shift
       ;;
 
-    -O1 | --optimization-level=1)
-      DART2WASM_ARGS+=(${OPT_FLAGS_L1[@]})
+    -O* | --optimization-level=*)
+      DART2WASM_ARGS+=("$1")
       RUN_BINARYEN=1
       shift
       ;;
 
-    -O2 | --optimization-level=2)
-      DART2WASM_ARGS+=(${OPT_FLAGS_L2[@]})
-      RUN_BINARYEN=1
-      shift
-      ;;
-
-    -O3 | --optimization-level=3)
-      DART2WASM_ARGS+=(${OPT_FLAGS_L3[@]})
-      RUN_BINARYEN=1
-      shift
-      ;;
-
-    -O4 | --optimization-level=4)
-      DART2WASM_ARGS+=(${OPT_FLAGS_L4[@]})
-      RUN_BINARYEN=1
+    --phases=*)
+      PHASES="${1#--phases=}"
       shift
       ;;
 
@@ -161,7 +142,7 @@ while [ $# -gt 0 ]; do
 
     -o)
       shift
-      WASM_FILE="$1"
+      OUTPUT_FILE="$1"
       shift
       ;;
 
@@ -175,8 +156,8 @@ while [ $# -gt 0 ]; do
         DART_FILE="$1"
         shift
       else
-        if [ -z "$WASM_FILE" ]; then
-          WASM_FILE="$1"
+        if [ -z "$OUTPUT_FILE" ]; then
+          OUTPUT_FILE="$1"
           shift
         else
           echo "Unexpected argument $1"
@@ -187,13 +168,31 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-if [ $GENERATE_SOURCE_MAP -eq 1 ]; then
-  BINARYEN_FLAGS+=("-ism" "${WASM_FILE}.map" "-osm" "${WASM_FILE}.map")
+if [ -z "$DART_FILE" ]; then
+  echo "Expected <file.dart> [file.wasm]"
+  exit 1
 fi
 
-if [ -z "$DART_FILE" -o -z "$WASM_FILE" ]; then
+if [ $USE_TEMP_OUTPUT -eq 1 ] && [ -n "$OUTPUT_FILE" ]; then
+  echo "Cannot specify both --temp-output and an explicit output file!"
+  exit 1
+fi
+
+if [ $USE_TEMP_OUTPUT -eq 0 ] && [ -z "$OUTPUT_FILE" ]; then
   echo "Expected <file.dart> <file.wasm>"
   exit 1
+fi
+
+if [ $USE_TEMP_OUTPUT -eq 1 ]; then
+  BASENAME=$(basename "$DART_FILE" .dart)
+  TEMP_DIR=$(mktemp -d)
+  trap "rm -rf $TEMP_DIR" EXIT
+  OUTPUT_FILE="$TEMP_DIR/${BASENAME}.wasm"
+  echo "Compiling to temporary file: $OUTPUT_FILE"
+fi
+
+if [ -z "$PHASES" ]; then
+  PHASES="cfe,tfa,codegen"
 fi
 
 
@@ -203,7 +202,7 @@ DART2WASM_SRC="$SDK_DIR/pkg/dart2wasm/bin/dart2wasm.dart"
 
 function measure() {
   set +e
-  RESULT=$( { /usr/bin/time --format="\nMemory: %M KB, Time: %e s" $@; } 2>&1 )
+  RESULT=$( { /usr/bin/time --format="\nMemory: %M KB, Time: %e s" "$@"; } 2>&1 )
   EXIT=$?
   if [ $EXIT -ne 0 ]; then
     echo "Running $@ resulted in exit code $EXIT"
@@ -222,45 +221,69 @@ function measure_size() {
 }
 
 function run_if_binaryen_enabled() {
-  if [ $RUN_BINARYEN -eq 1 ]; then
-    $@
+  if [ $RUN_BINARYEN -eq 1 ] && [[ $OUTPUT_FILE == *.wasm ]]; then
+    "$@"
   fi
 }
 
+COMPILER_SIZE=0
+COMPILER_GZIP_SIZE=0
+
 if [ $RUN_SRC -eq 1 ]; then
-  dart2wasm_command=("$DART" "${VM_ARGS[@]}" "$DART2WASM_SRC" "$LIBRARIES_JSON_ARG" "${DART2WASM_ARGS[@]}" "$DART_FILE" "$WASM_FILE")
+  BASE_CMD=("$DART" "${VM_ARGS[@]}" "$DART2WASM_SRC" "$LIBRARIES_JSON_ARG")
 else
-  dart2wasm_command=("$DART_AOT_RUNTIME" "${VM_ARGS[@]}" "$DART2WASM_AOT_SNAPSHOT" "$PLATFORM_ARG" "${DART2WASM_ARGS[@]}" "$DART_FILE" "$WASM_FILE")
+  BASE_CMD=("$DART_AOT_RUNTIME" "${VM_ARGS[@]}" "$DART2WASM_AOT_SNAPSHOT" "$PLATFORM_ARG")
 fi
 
-binaryen_command=("$BINARYEN" "${BINARYEN_FLAGS[@]}" "$WASM_FILE" -o "$WASM_FILE")
+function run_compiler() {
+  local dart2wasm_command=("${BASE_CMD[@]}" "${DART2WASM_ARGS[@]}" "--phases=$PHASES" "$DART_FILE" "$OUTPUT_FILE")
+
+  if [ -n "$COMPILE_BENCHMARK_BASE_NAME" ]; then
+    measure "${dart2wasm_command[@]}"
+    COMPILER_TIME=$TIME
+    COMPILER_MEMORY=$MEMORY
+
+    measure_size "${OUTPUT_FILE%.wasm}.mjs"
+    MJS_SIZE=$SIZE
+    MJS_GZIP_SIZE=$GZIP_SIZE
+
+    for OUTPUT_FILE in "${OUTPUT_FILE%.wasm}"*.wasm; do
+      measure_size "$OUTPUT_FILE"
+      (( COMPILER_SIZE+=$SIZE ))
+      (( COMPILER_GZIP_SIZE+=$GZIP_SIZE ))
+    done
+  else
+    "${dart2wasm_command[@]}"
+  fi
+}
+
+BINARYEN_TIME=0
+BINARYEN_MEMORY=0
+BINARYEN_SIZE=0
+BINARYEN_GZIP_SIZE=0
+
+function run_binaryen() {
+  local opt_command=("${BASE_CMD[@]}" "${DART2WASM_ARGS[@]}" "--phases=opt" "--wasm-opt=$BINARYEN" "$OUTPUT_FILE" "$OUTPUT_FILE")
+
+  if [ -n "$COMPILE_BENCHMARK_BASE_NAME" ]; then
+    # If we're measuring run each binaryen command sequentially.
+    measure "${opt_command[@]}"
+    BINARYEN_TIME=$(echo "$BINARYEN_TIME + $TIME" | bc)
+    BINARYEN_MEMORY=$(($BINARYEN_MEMORY > $MEMORY ? $BINARYEN_MEMORY : $MEMORY ))
+    measure_size "$OUTPUT_FILE"
+    BINARYEN_SIZE=$(echo "$BINARYEN_SIZE + $SIZE" | bc)
+    BINARYEN_GZIP_SIZE=$(echo "$BINARYEN_GZIP_SIZE + $GZIP_SIZE" | bc)
+    MAX_MEMORY=$(($COMPILER_MEMORY > $BINARYEN_MEMORY ? $COMPILER_MEMORY : $BINARYEN_MEMORY ))
+    TOTAL_TIME=$(echo "$COMPILER_TIME + $BINARYEN_TIME" | bc)
+  else
+    "${opt_command[@]}"
+  fi
+}
+
+run_compiler
+run_if_binaryen_enabled run_binaryen
 
 if [ -n "$COMPILE_BENCHMARK_BASE_NAME" ]; then
-  measure "${dart2wasm_command[@]}"
-  COMPILER_TIME=$TIME
-  COMPILER_MEMORY=$MEMORY
-
-  measure_size ${WASM_FILE%.wasm}.mjs
-  MJS_SIZE=$SIZE
-  MJS_GZIP_SIZE=$GZIP_SIZE
-
-  measure_size $WASM_FILE
-  COMPILER_SIZE=$SIZE
-  COMPILER_GZIP_SIZE=$GZIP_SIZE
-
-  if [ $RUN_BINARYEN -eq 1 ]; then
-    measure ${binaryen_command[@]}
-    BINARYEN_TIME=$TIME
-    BINARYEN_MEMORY=$MEMORY
-
-    measure_size $WASM_FILE
-    BINARYEN_SIZE=$SIZE
-    BINARYEN_GZIP_SIZE=$GZIP_SIZE
-
-    TOTAL_TIME=$(echo "$COMPILER_TIME + $BINARYEN_TIME" | bc)
-    MAX_MEMORY=$(($COMPILER_MEMORY > $BINARYEN_MEMORY ? $COMPILER_MEMORY : $BINARYEN_MEMORY ))
-  fi
-
   # CompileTime
   run_if_binaryen_enabled echo "$COMPILE_BENCHMARK_BASE_NAME.Time.Total(CompileTime): $TOTAL_TIME s"
   echo "$COMPILE_BENCHMARK_BASE_NAME.Time.Dart2Wasm(CompileTime): $COMPILER_TIME s"
@@ -275,10 +298,13 @@ if [ -n "$COMPILE_BENCHMARK_BASE_NAME" ]; then
   run_if_binaryen_enabled echo "$COMPILE_BENCHMARK_BASE_NAME.Size.wasm.opt.gz(CodeSize): $BINARYEN_GZIP_SIZE bytes"
 
   # MemoryUse
-  echo "$COMPILE_BENCHMARK_BASE_NAME.MemoryUse.Max(MemoryUse): $MAX_MEMORY bytes"
+  run_if_binaryen_enabled echo "$COMPILE_BENCHMARK_BASE_NAME.MemoryUse.Max(MemoryUse): $MAX_MEMORY bytes"
   echo "$COMPILE_BENCHMARK_BASE_NAME.MemoryUse.Dart2Wasm(MemoryUse): $COMPILER_MEMORY bytes"
   run_if_binaryen_enabled echo "$COMPILE_BENCHMARK_BASE_NAME.MemoryUse.Wasm2WasmOpt(MemoryUse): $BINARYEN_MEMORY bytes"
-else
-  "${dart2wasm_command[@]}"
-  run_if_binaryen_enabled ${binaryen_command[@]}
+fi
+
+if [ $RUN_BENCHMARK -eq 1 ]; then
+  echo ""
+  echo "RUNNING $OUTPUT_FILE"
+  "$PROG_DIR/run_benchmark" "--$RUN_BENCHMARK_SHELL" "$OUTPUT_FILE"
 fi
