update pkg to dart 3.9.2

diff --git a/inner/pkg/vm/tool/precompiler2 b/inner/pkg/vm/tool/precompiler2
--- a/inner/pkg/vm/tool/precompiler2
+++ b/inner/pkg/vm/tool/precompiler2
@@ -14,6 +14,25 @@
 
 set -e
 
+function follow_links() {
+  local file="$1"
+  while [ -h "$file" ]; do
+    # On Mac OS, readlink -f doesn't work.
+    file="$(readlink "$file")"
+  done
+  echo "$file"
+}
+
+# Unlike $0, $BASH_SOURCE points to the absolute path of this file.
+PROG_NAME="$(follow_links "$BASH_SOURCE")"
+
+# Handle the case where dart-sdk/bin has been symlinked to.
+CUR_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
+
+SDK_DIR="$CUR_DIR/../../.."
+
+. "$CUR_DIR/shared_functions.sh"
+
 OPTIONS=()
 GEN_KERNEL_OPTIONS=()
 PACKAGES=
@@ -22,6 +41,9 @@ BUILD_ASM=0
 ARGV=()
 for arg in "$@"; do
   case $arg in
+    --packages=sdk)
+    PACKAGES="$SDK_DIR/.dart_tool/package_config.json"
+    ;;
     --packages=*)
     PACKAGES="$arg"
     ;;
@@ -37,6 +59,7 @@ for arg in "$@"; do
     --protobuf-tree-shaker-v2 | \
     --minimal-kernel | \
     --no-embed-sources | \
+    --dynamic-interface=* | \
     -D* )
     GEN_KERNEL_OPTIONS+=("$arg")
     ;;
@@ -71,50 +94,85 @@ else
   GEN_SNAPSHOT_FILENAME="--elf=${SNAPSHOT_FILE}"
 fi
 
-function follow_links() {
-  file="$1"
-  while [ -h "$file" ]; do
-    # On Mac OS, readlink -f doesn't work.
-    file="$(readlink "$file")"
-  done
-  echo "$file"
-}
-
-# Unlike $0, $BASH_SOURCE points to the absolute path of this file.
-PROG_NAME="$(follow_links "$BASH_SOURCE")"
-
-# Handle the case where dart-sdk/bin has been symlinked to.
-CUR_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
-
-SDK_DIR="$CUR_DIR/../../.."
-
 if [[ `uname` == 'Darwin' ]]; then
   OUT_DIR="$SDK_DIR/xcodebuild"
 else
   OUT_DIR="$SDK_DIR/out"
 fi
 
-export DART_CONFIGURATION=${DART_CONFIGURATION:-ReleaseX64}
-BIN_DIR="$OUT_DIR/$DART_CONFIGURATION"
+HOST_ARCH="$(host_arch)"
 
-DART="${SDK_DIR}/tools/sdks/dart-sdk/bin/dart"
-if [ ! -f "$DART" ]; then
-  DART="$BIN_DIR/dart"
+export DART_CONFIGURATION=${DART_CONFIGURATION:-Release$HOST_ARCH}
+TARGET_ARCH="$(parse_target_arch "$DART_CONFIGURATION")"
+BUILD_DIR="$OUT_DIR/$DART_CONFIGURATION"
+if [ ! -d "$BUILD_DIR" ]; then
+  echo "$BUILD_DIR is not a directory" >&2
+  exit 1
 fi
 
+function find_dart {
+  local tools_dart="${SDK_DIR}/tools/sdks/dart-sdk/bin/dart"
+  if [ -f "$tools_dart" ]; then
+    echo "$tools_dart"
+  else
+    local host_dart=""
+    if is_cross_compiled "$HOST_ARCH" "$TARGET_ARCH"; then
+      host_dart="$OUT_DIR/Release$HOST_ARCH/dart"
+    else
+      host_dart="$BUILD_DIR/dart"
+    fi
+    if [ ! -f "$host_dart" ]; then
+      echo "Cannot find dart at either $tools_dart or $host_dart" >&2
+      exit 1
+    fi
+    echo "$host_dart"
+  fi
+}
+
+DART="$(find_dart)"
+
+function gen_kernel() {
+  if [[ "$DART_GN_ARGS" == *"precompile_tools=true"* ]]; then
+    # Precompile gen_kernel to an AOT app.
+    ninja -C "$BUILD_DIR" gen_kernel.exe
+    "$BUILD_DIR/gen_kernel.exe" $@
+  else
+    $DART ${DART_VM_FLAGS} "${SDK_DIR}/pkg/vm/bin/gen_kernel.dart" $@
+  fi
+}
+
 # Step 1: Generate Kernel binary from the input Dart source.
-$DART                                                                          \
-     ${DART_VM_FLAGS}                                                          \
-     "${SDK_DIR}/pkg/vm/bin/gen_kernel.dart"                                   \
-     --platform "${BIN_DIR}/vm_platform_strong.dill"                           \
+gen_kernel --platform "${BUILD_DIR}/vm_platform.dill"                   \
      --aot                                                                     \
      "${GEN_KERNEL_OPTIONS[@]}"                                                \
      $PACKAGES                                                                 \
      -o "$SNAPSHOT_FILE.dill"                                                  \
      "$SOURCE_FILE"
 
+GEN_SNAPSHOT="gen_snapshot"
+# If the target architecture differs from the host architecture, use
+# gen_snapshot for the host architecture for cross compilation, which is
+# denoted by an X between the build mode and the architecture name,
+# e.g., ReleaseXARM64 on X64.
+if [[ "$DART_CONFIGURATION" =~ (Debug|Release|Product)X[^6] ]] && \
+      is_cross_compiled "$HOST_ARCH" "$TARGET_ARCH"; then
+  case "$HOST_ARCH" in
+    "X64")
+    GEN_SNAPSHOT="clang_x64/${GEN_SNAPSHOT}"
+    ;;
+    "ARM64")
+    GEN_SNAPSHOT="clang_arm64/${GEN_SNAPSHOT}"
+    ;;
+    *)
+    echo "Unexpected host architecture $HOST_ARCH for cross compilation" >&2
+    exit 1
+    ;;
+  esac
+fi
+
 # Step 2: Generate snapshot from the Kernel binary.
-"$BIN_DIR"/gen_snapshot                                                        \
+${BUILD_DIR}/${GEN_SNAPSHOT}                                                   \
+     ${GEN_SNAPSHOT_FLAGS}                                                     \
      "$GEN_SNAPSHOT_OPTION"                                                    \
      "$GEN_SNAPSHOT_FILENAME"                                                  \
      "${OPTIONS[@]}"                                                           \
